# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_organizers',
        ),
        migrations.AddField(
            model_name='group',
            name='group_organizers',
            field=models.ManyToManyField(to='rapipd.Organizer'),
        ),
    ]
